#!/bin/bash
echo "╔════════════════════════════════════╗"
echo "║⏳  Installing Python dependencies...║"
echo "╚════════════════════════════════════╝"
python3 -m venv env && source env/bin/activate && \
	pip3 install --upgrade pip && \
	pip3 install https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-0.12.1-py3-none-any.whl && \
	pip3 install keras lasagne jupyter ipython numpy scipy matplotlib
echo "╔═════════╗"
echo "║✅  Done. ║"
echo "╚═════════╝"
